### ISSUE TITLE
Does it work with Sky Q?

### ISSUE THREAD

**Issue by mallchin** [ndg63276/alexa-sky-hd#1]

**Comment by ndg63276** [comment]
I believe so, provided your firmware version is 0.60 or above. But I don't have a Sky Q box to test it with.

**Comment by rosstilley** [comment]
I can confirm that this does indeed work with Sky Q, albeit with some quirks because of differences with controling a standard Sky HD box.

It’d be good if there was a way of including controls that make use of Sky Q’s features. Opening specific apps like Netflix for example, or jumping straight to your recordings.

Does anyone know if it’s possible to send these commands using Q’s IP controls?

It must be possible in some form because you can use Sky’s voice controls to jump to these areas. 

Does anyone know or know if there’s a way to find out?

R

**Comment by ndg63276** [comment]
See ticket #2.
