### ISSUE TITLE
Adding Sky Italy channel

### ISSUE THREAD

**Issue by stich86** [ndg63276/alexa-sky-hd#6]
Hi,

do you know if it's possible to add Sky Italy channel?
I've found the channel list, but it's not in JSON format

http://www.webgrabplus.com/sites/default/files/download/ini/info/siteini.pack/Italy/guidatv.sky.it.channels.xml

i've another question: where are the language utterance to spell the channel name?

thanks!

**Comment by ndg63276** [comment]
It might be possible, can you test if it works with just channel numbers for now? "Alexa, change channel to 101 on Sky Box"?

That list of channels, do they have numbers?

There aren't any language utterances because it is a smart home skill, so when you say "change channel", it just sends a ChangeChannel request with whatever you say. The skill tries to figure out if it was a number or name, and if it was a name, converts to a number.

**Comment by stich86** [comment]
it looks like that i cannot do in my language :(

channel controll are still not avaliable on italian language

**Comment by ndg63276** [comment]
That's a shame (for my reference, list of available languages and events at https://developer.amazon.com/docs/device-apis/list-of-interfaces.html). 

It looks like you can use the PowerController, which can turn the Sky box on or off, which is quite useful.

If you are interested in creating (unofficial) Alexa skills, I would recommend my Youtube skill, at https://github.com/ndg63276/alexa-youtube.
